## **TASK 2**

Cholesky Decomposition is used in this code for constructing valid covariance matrix which will help us to get multiple samples of gaussian distribution for N=3 and N=5. In, reality we need our base covariance matrix positive definite (basic for gaussian distribution). 

---

Covariance matrix should be positive definite and for generating samples i have used np.random.mormal()

In [10]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()
 
# Define dimension. 
d = 3
# Set mean vector. 
m_3 = np.array([1, 2, 3]).reshape(3, 1)
# Set covariance function. Positive Definite
K_3 = np.array([[2, -1, 0],
                [-1, 2, -1], 
                [0, -1, 2]])

#print(np.linalg.eigvals(K_3))
epsilon = 0.0001 # For noise

# Add small pertturbation. 
K = K_3 + epsilon*np.identity(d)

#  Cholesky decomposition.
L = np.linalg.cholesky(K)

#print(L)
#print(np.dot(L, np.transpose(L)))
 
# Number of samples. 
n = 10000
u = np.random.normal(loc=0, scale=1, size=d*n).reshape(d, n)
x_3 = m_3 + np.dot(L, u)
print(' ')
print('BELOW ARE GENERATED 3-D SAMPLES')
print(x_3.shape)
print(' ')
print(x_3)
#sns.jointplot(x=x[0], y=x[1], kind="kde", space=0);

 
BELOW ARE GENERATED 3-D SAMPLES
(3, 10000)
 
[[0.66358075 0.57932334 2.51422916 ... 1.48340453 2.02684266 1.74343072]
 [2.57099125 2.02355176 1.6810126  ... 3.12192499 1.32809613 3.32883407]
 [4.68654933 3.34469483 1.62277438 ... 2.32420348 1.87670839 2.32114827]]


In [11]:
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

# Define dimension. 
d = 5
# Set mean vector. 
m_5 = np.array([1, 2, 3, 4, 5]).reshape(5, 1)
# Set covariance function. 
# A Toeplitz matrix with eigen value 0.5484316
K_5 = np.array([[5, 4, 3, 2, 1],
                [4, 5, 4, 3, 2],
                [3, 4, 5, 4, 3],
                [2, 3, 4, 5, 4], 
                [1, 2, 3, 4, 5]])
#print(np.linalg.eigvals(K_5))

epsilon = 0.0001 # For noise 
# Add small pertturbation. 
K = K_5 + epsilon*np.identity(d)

#  Cholesky decomposition.
L = np.linalg.cholesky(K)
#print(L)
#print(np.dot(L, np.transpose(L)))


# Number of samples. 
n = 10000

u = np.random.normal(loc=0, scale=1, size=d*n).reshape(d, n)
x_5 = m_5 + np.dot(L, u)
print(' ')
print('BELOW ARE GENERATED 5-D SAMPLES')
print(x_5.shape)
print(' ')
print(x_5)
#sns.jointplot(x=x[0], y=x[1], kind="kde", space=0);

 
BELOW ARE GENERATED 5-D SAMPLES
(5, 10000)
 
[[ 2.247744    1.76049145  1.49146641 ... -1.370183    0.52709458
   4.549873  ]
 [-0.31038131  2.55582661  1.02122686 ...  0.80050714  3.10906317
   4.78677108]
 [ 0.95418538  2.4217553   1.18133553 ... -0.6321145   5.71604608
   6.25488818]
 [ 2.72819449  3.52135292  2.77586922 ... -0.59460381  4.26626331
   4.76972464]
 [ 3.61853754  2.87075377  3.71282917 ...  2.69061058  3.54288804
   4.08296364]]
